import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import Loading from "@/components/Loader/indext";
import { GlobalDataProvider } from "../../contexts/GlobalDataContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <GlobalDataProvider>
      <html lang="en">
        <body className={inter.className}>
          <Loading />
          {children}
          <ToastContainer />
        </body>
      </html>
    </GlobalDataProvider>
  );
}
